# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import robot_service_pb2 as teleop__follower_dot_proto_dot_robot__service__pb2


class RobotServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ResetDrivers = channel.unary_unary(
                '/robot_service.RobotService/ResetDrivers',
                request_serializer=teleop__follower_dot_proto_dot_robot__service__pb2.ResetDriversRequest.SerializeToString,
                response_deserializer=teleop__follower_dot_proto_dot_robot__service__pb2.ResetDriversResponse.FromString,
                _registered_method=True)
        self.ResetRobot = channel.unary_unary(
                '/robot_service.RobotService/ResetRobot',
                request_serializer=teleop__follower_dot_proto_dot_robot__service__pb2.ResetRobotRequest.SerializeToString,
                response_deserializer=teleop__follower_dot_proto_dot_robot__service__pb2.ResetRobotResponse.FromString,
                _registered_method=True)
        self.ResetVision = channel.unary_unary(
                '/robot_service.RobotService/ResetVision',
                request_serializer=teleop__follower_dot_proto_dot_robot__service__pb2.ResetVisionRequest.SerializeToString,
                response_deserializer=teleop__follower_dot_proto_dot_robot__service__pb2.ResetVisionResponse.FromString,
                _registered_method=True)
        self.MoveToJointGoal = channel.unary_unary(
                '/robot_service.RobotService/MoveToJointGoal',
                request_serializer=teleop__follower_dot_proto_dot_robot__service__pb2.MoveToJointGoalRequest.SerializeToString,
                response_deserializer=teleop__follower_dot_proto_dot_robot__service__pb2.MoveToJointGoalResponse.FromString,
                _registered_method=True)
        self.RecoverErrors = channel.unary_unary(
                '/robot_service.RobotService/RecoverErrors',
                request_serializer=teleop__follower_dot_proto_dot_robot__service__pb2.RecoverErrorsRequest.SerializeToString,
                response_deserializer=teleop__follower_dot_proto_dot_robot__service__pb2.RecoverErrorsResponse.FromString,
                _registered_method=True)
        self.PrepareExecution = channel.unary_unary(
                '/robot_service.RobotService/PrepareExecution',
                request_serializer=teleop__follower_dot_proto_dot_robot__service__pb2.PrepareExecutionRequest.SerializeToString,
                response_deserializer=teleop__follower_dot_proto_dot_robot__service__pb2.PrepareExecutionResponse.FromString,
                _registered_method=True)
        self.GetState = channel.unary_unary(
                '/robot_service.RobotService/GetState',
                request_serializer=teleop__follower_dot_proto_dot_robot__service__pb2.GetStateRequest.SerializeToString,
                response_deserializer=teleop__follower_dot_proto_dot_robot__service__pb2.GetStateResponse.FromString,
                _registered_method=True)
        self.StreamState = channel.unary_stream(
                '/robot_service.RobotService/StreamState',
                request_serializer=teleop__follower_dot_proto_dot_robot__service__pb2.StreamStateRequest.SerializeToString,
                response_deserializer=teleop__follower_dot_proto_dot_robot__service__pb2.State.FromString,
                _registered_method=True)
        self.EnqueueCartesianWaypoints = channel.unary_unary(
                '/robot_service.RobotService/EnqueueCartesianWaypoints',
                request_serializer=teleop__follower_dot_proto_dot_robot__service__pb2.EnqueueCartesianWaypointsRequest.SerializeToString,
                response_deserializer=teleop__follower_dot_proto_dot_robot__service__pb2.EnqueueCartesianWaypointsResponse.FromString,
                _registered_method=True)
        self.SetCartesianTarget = channel.unary_unary(
                '/robot_service.RobotService/SetCartesianTarget',
                request_serializer=teleop__follower_dot_proto_dot_robot__service__pb2.SetCartesianTargetRequest.SerializeToString,
                response_deserializer=teleop__follower_dot_proto_dot_robot__service__pb2.SetCartesianTargetResponse.FromString,
                _registered_method=True)
        self.SetJointTarget = channel.unary_unary(
                '/robot_service.RobotService/SetJointTarget',
                request_serializer=teleop__follower_dot_proto_dot_robot__service__pb2.SetJointTargetRequest.SerializeToString,
                response_deserializer=teleop__follower_dot_proto_dot_robot__service__pb2.SetJointTargetResponse.FromString,
                _registered_method=True)
        self.StreamJointTargets = channel.stream_unary(
                '/robot_service.RobotService/StreamJointTargets',
                request_serializer=teleop__follower_dot_proto_dot_robot__service__pb2.JointTarget.SerializeToString,
                response_deserializer=teleop__follower_dot_proto_dot_robot__service__pb2.StreamJointTargetsResponse.FromString,
                _registered_method=True)
        self.StreamCartesianTargets = channel.stream_unary(
                '/robot_service.RobotService/StreamCartesianTargets',
                request_serializer=teleop__follower_dot_proto_dot_robot__service__pb2.CartesianTarget.SerializeToString,
                response_deserializer=teleop__follower_dot_proto_dot_robot__service__pb2.StreamCartesianTargetsResponse.FromString,
                _registered_method=True)
        self.SetCartesianWaypoint = channel.unary_unary(
                '/robot_service.RobotService/SetCartesianWaypoint',
                request_serializer=teleop__follower_dot_proto_dot_robot__service__pb2.SetCartesianWaypointRequest.SerializeToString,
                response_deserializer=teleop__follower_dot_proto_dot_robot__service__pb2.SetCartesianWaypointResponse.FromString,
                _registered_method=True)
        self.StreamCartesianWaypoints = channel.stream_unary(
                '/robot_service.RobotService/StreamCartesianWaypoints',
                request_serializer=teleop__follower_dot_proto_dot_robot__service__pb2.CartesianTarget.SerializeToString,
                response_deserializer=teleop__follower_dot_proto_dot_robot__service__pb2.StreamCartesianWaypointsResponse.FromString,
                _registered_method=True)
        self.VisualizeCartesianTargetActionChunk = channel.unary_unary(
                '/robot_service.RobotService/VisualizeCartesianTargetActionChunk',
                request_serializer=teleop__follower_dot_proto_dot_robot__service__pb2.VisualizeCartesianTargetActionChunkRequest.SerializeToString,
                response_deserializer=teleop__follower_dot_proto_dot_robot__service__pb2.VisualizeCartesianTargetActionChunkResponse.FromString,
                _registered_method=True)
        self.VisualizeJointConfigurationPath = channel.unary_unary(
                '/robot_service.RobotService/VisualizeJointConfigurationPath',
                request_serializer=teleop__follower_dot_proto_dot_robot__service__pb2.VisualizeJointConfigurationPathRequest.SerializeToString,
                response_deserializer=teleop__follower_dot_proto_dot_robot__service__pb2.VisualizeJointConfigurationPathResponse.FromString,
                _registered_method=True)
        self.SetGripperState = channel.unary_unary(
                '/robot_service.RobotService/SetGripperState',
                request_serializer=teleop__follower_dot_proto_dot_robot__service__pb2.SetGripperStateRequest.SerializeToString,
                response_deserializer=teleop__follower_dot_proto_dot_robot__service__pb2.SetGripperStateResponse.FromString,
                _registered_method=True)


class RobotServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ResetDrivers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetRobot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetVision(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MoveToJointGoal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecoverErrors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PrepareExecution(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnqueueCartesianWaypoints(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetCartesianTarget(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetJointTarget(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamJointTargets(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamCartesianTargets(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetCartesianWaypoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamCartesianWaypoints(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VisualizeCartesianTargetActionChunk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VisualizeJointConfigurationPath(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetGripperState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RobotServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ResetDrivers': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetDrivers,
                    request_deserializer=teleop__follower_dot_proto_dot_robot__service__pb2.ResetDriversRequest.FromString,
                    response_serializer=teleop__follower_dot_proto_dot_robot__service__pb2.ResetDriversResponse.SerializeToString,
            ),
            'ResetRobot': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetRobot,
                    request_deserializer=teleop__follower_dot_proto_dot_robot__service__pb2.ResetRobotRequest.FromString,
                    response_serializer=teleop__follower_dot_proto_dot_robot__service__pb2.ResetRobotResponse.SerializeToString,
            ),
            'ResetVision': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetVision,
                    request_deserializer=teleop__follower_dot_proto_dot_robot__service__pb2.ResetVisionRequest.FromString,
                    response_serializer=teleop__follower_dot_proto_dot_robot__service__pb2.ResetVisionResponse.SerializeToString,
            ),
            'MoveToJointGoal': grpc.unary_unary_rpc_method_handler(
                    servicer.MoveToJointGoal,
                    request_deserializer=teleop__follower_dot_proto_dot_robot__service__pb2.MoveToJointGoalRequest.FromString,
                    response_serializer=teleop__follower_dot_proto_dot_robot__service__pb2.MoveToJointGoalResponse.SerializeToString,
            ),
            'RecoverErrors': grpc.unary_unary_rpc_method_handler(
                    servicer.RecoverErrors,
                    request_deserializer=teleop__follower_dot_proto_dot_robot__service__pb2.RecoverErrorsRequest.FromString,
                    response_serializer=teleop__follower_dot_proto_dot_robot__service__pb2.RecoverErrorsResponse.SerializeToString,
            ),
            'PrepareExecution': grpc.unary_unary_rpc_method_handler(
                    servicer.PrepareExecution,
                    request_deserializer=teleop__follower_dot_proto_dot_robot__service__pb2.PrepareExecutionRequest.FromString,
                    response_serializer=teleop__follower_dot_proto_dot_robot__service__pb2.PrepareExecutionResponse.SerializeToString,
            ),
            'GetState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetState,
                    request_deserializer=teleop__follower_dot_proto_dot_robot__service__pb2.GetStateRequest.FromString,
                    response_serializer=teleop__follower_dot_proto_dot_robot__service__pb2.GetStateResponse.SerializeToString,
            ),
            'StreamState': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamState,
                    request_deserializer=teleop__follower_dot_proto_dot_robot__service__pb2.StreamStateRequest.FromString,
                    response_serializer=teleop__follower_dot_proto_dot_robot__service__pb2.State.SerializeToString,
            ),
            'EnqueueCartesianWaypoints': grpc.unary_unary_rpc_method_handler(
                    servicer.EnqueueCartesianWaypoints,
                    request_deserializer=teleop__follower_dot_proto_dot_robot__service__pb2.EnqueueCartesianWaypointsRequest.FromString,
                    response_serializer=teleop__follower_dot_proto_dot_robot__service__pb2.EnqueueCartesianWaypointsResponse.SerializeToString,
            ),
            'SetCartesianTarget': grpc.unary_unary_rpc_method_handler(
                    servicer.SetCartesianTarget,
                    request_deserializer=teleop__follower_dot_proto_dot_robot__service__pb2.SetCartesianTargetRequest.FromString,
                    response_serializer=teleop__follower_dot_proto_dot_robot__service__pb2.SetCartesianTargetResponse.SerializeToString,
            ),
            'SetJointTarget': grpc.unary_unary_rpc_method_handler(
                    servicer.SetJointTarget,
                    request_deserializer=teleop__follower_dot_proto_dot_robot__service__pb2.SetJointTargetRequest.FromString,
                    response_serializer=teleop__follower_dot_proto_dot_robot__service__pb2.SetJointTargetResponse.SerializeToString,
            ),
            'StreamJointTargets': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamJointTargets,
                    request_deserializer=teleop__follower_dot_proto_dot_robot__service__pb2.JointTarget.FromString,
                    response_serializer=teleop__follower_dot_proto_dot_robot__service__pb2.StreamJointTargetsResponse.SerializeToString,
            ),
            'StreamCartesianTargets': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamCartesianTargets,
                    request_deserializer=teleop__follower_dot_proto_dot_robot__service__pb2.CartesianTarget.FromString,
                    response_serializer=teleop__follower_dot_proto_dot_robot__service__pb2.StreamCartesianTargetsResponse.SerializeToString,
            ),
            'SetCartesianWaypoint': grpc.unary_unary_rpc_method_handler(
                    servicer.SetCartesianWaypoint,
                    request_deserializer=teleop__follower_dot_proto_dot_robot__service__pb2.SetCartesianWaypointRequest.FromString,
                    response_serializer=teleop__follower_dot_proto_dot_robot__service__pb2.SetCartesianWaypointResponse.SerializeToString,
            ),
            'StreamCartesianWaypoints': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamCartesianWaypoints,
                    request_deserializer=teleop__follower_dot_proto_dot_robot__service__pb2.CartesianTarget.FromString,
                    response_serializer=teleop__follower_dot_proto_dot_robot__service__pb2.StreamCartesianWaypointsResponse.SerializeToString,
            ),
            'VisualizeCartesianTargetActionChunk': grpc.unary_unary_rpc_method_handler(
                    servicer.VisualizeCartesianTargetActionChunk,
                    request_deserializer=teleop__follower_dot_proto_dot_robot__service__pb2.VisualizeCartesianTargetActionChunkRequest.FromString,
                    response_serializer=teleop__follower_dot_proto_dot_robot__service__pb2.VisualizeCartesianTargetActionChunkResponse.SerializeToString,
            ),
            'VisualizeJointConfigurationPath': grpc.unary_unary_rpc_method_handler(
                    servicer.VisualizeJointConfigurationPath,
                    request_deserializer=teleop__follower_dot_proto_dot_robot__service__pb2.VisualizeJointConfigurationPathRequest.FromString,
                    response_serializer=teleop__follower_dot_proto_dot_robot__service__pb2.VisualizeJointConfigurationPathResponse.SerializeToString,
            ),
            'SetGripperState': grpc.unary_unary_rpc_method_handler(
                    servicer.SetGripperState,
                    request_deserializer=teleop__follower_dot_proto_dot_robot__service__pb2.SetGripperStateRequest.FromString,
                    response_serializer=teleop__follower_dot_proto_dot_robot__service__pb2.SetGripperStateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'robot_service.RobotService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('robot_service.RobotService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RobotService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ResetDrivers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot_service.RobotService/ResetDrivers',
            teleop__follower_dot_proto_dot_robot__service__pb2.ResetDriversRequest.SerializeToString,
            teleop__follower_dot_proto_dot_robot__service__pb2.ResetDriversResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetRobot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot_service.RobotService/ResetRobot',
            teleop__follower_dot_proto_dot_robot__service__pb2.ResetRobotRequest.SerializeToString,
            teleop__follower_dot_proto_dot_robot__service__pb2.ResetRobotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetVision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot_service.RobotService/ResetVision',
            teleop__follower_dot_proto_dot_robot__service__pb2.ResetVisionRequest.SerializeToString,
            teleop__follower_dot_proto_dot_robot__service__pb2.ResetVisionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MoveToJointGoal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot_service.RobotService/MoveToJointGoal',
            teleop__follower_dot_proto_dot_robot__service__pb2.MoveToJointGoalRequest.SerializeToString,
            teleop__follower_dot_proto_dot_robot__service__pb2.MoveToJointGoalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecoverErrors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot_service.RobotService/RecoverErrors',
            teleop__follower_dot_proto_dot_robot__service__pb2.RecoverErrorsRequest.SerializeToString,
            teleop__follower_dot_proto_dot_robot__service__pb2.RecoverErrorsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PrepareExecution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot_service.RobotService/PrepareExecution',
            teleop__follower_dot_proto_dot_robot__service__pb2.PrepareExecutionRequest.SerializeToString,
            teleop__follower_dot_proto_dot_robot__service__pb2.PrepareExecutionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot_service.RobotService/GetState',
            teleop__follower_dot_proto_dot_robot__service__pb2.GetStateRequest.SerializeToString,
            teleop__follower_dot_proto_dot_robot__service__pb2.GetStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/robot_service.RobotService/StreamState',
            teleop__follower_dot_proto_dot_robot__service__pb2.StreamStateRequest.SerializeToString,
            teleop__follower_dot_proto_dot_robot__service__pb2.State.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnqueueCartesianWaypoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot_service.RobotService/EnqueueCartesianWaypoints',
            teleop__follower_dot_proto_dot_robot__service__pb2.EnqueueCartesianWaypointsRequest.SerializeToString,
            teleop__follower_dot_proto_dot_robot__service__pb2.EnqueueCartesianWaypointsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetCartesianTarget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot_service.RobotService/SetCartesianTarget',
            teleop__follower_dot_proto_dot_robot__service__pb2.SetCartesianTargetRequest.SerializeToString,
            teleop__follower_dot_proto_dot_robot__service__pb2.SetCartesianTargetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetJointTarget(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot_service.RobotService/SetJointTarget',
            teleop__follower_dot_proto_dot_robot__service__pb2.SetJointTargetRequest.SerializeToString,
            teleop__follower_dot_proto_dot_robot__service__pb2.SetJointTargetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamJointTargets(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/robot_service.RobotService/StreamJointTargets',
            teleop__follower_dot_proto_dot_robot__service__pb2.JointTarget.SerializeToString,
            teleop__follower_dot_proto_dot_robot__service__pb2.StreamJointTargetsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamCartesianTargets(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/robot_service.RobotService/StreamCartesianTargets',
            teleop__follower_dot_proto_dot_robot__service__pb2.CartesianTarget.SerializeToString,
            teleop__follower_dot_proto_dot_robot__service__pb2.StreamCartesianTargetsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetCartesianWaypoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot_service.RobotService/SetCartesianWaypoint',
            teleop__follower_dot_proto_dot_robot__service__pb2.SetCartesianWaypointRequest.SerializeToString,
            teleop__follower_dot_proto_dot_robot__service__pb2.SetCartesianWaypointResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamCartesianWaypoints(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/robot_service.RobotService/StreamCartesianWaypoints',
            teleop__follower_dot_proto_dot_robot__service__pb2.CartesianTarget.SerializeToString,
            teleop__follower_dot_proto_dot_robot__service__pb2.StreamCartesianWaypointsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VisualizeCartesianTargetActionChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot_service.RobotService/VisualizeCartesianTargetActionChunk',
            teleop__follower_dot_proto_dot_robot__service__pb2.VisualizeCartesianTargetActionChunkRequest.SerializeToString,
            teleop__follower_dot_proto_dot_robot__service__pb2.VisualizeCartesianTargetActionChunkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VisualizeJointConfigurationPath(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot_service.RobotService/VisualizeJointConfigurationPath',
            teleop__follower_dot_proto_dot_robot__service__pb2.VisualizeJointConfigurationPathRequest.SerializeToString,
            teleop__follower_dot_proto_dot_robot__service__pb2.VisualizeJointConfigurationPathResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetGripperState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robot_service.RobotService/SetGripperState',
            teleop__follower_dot_proto_dot_robot__service__pb2.SetGripperStateRequest.SerializeToString,
            teleop__follower_dot_proto_dot_robot__service__pb2.SetGripperStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
