lerobot-train \
    --job_name=smolvla_pick_and_place \
    --output_dir=/root/autodl-tmp/outputs/smolvla_pick_and_place/ \
    --dataset.repo_id=continuallearning/pick_and_place_red_blocks \
    --policy.path=lerobot/smolvla_base \
    --policy.push_to_hub=false \
    --policy.scheduler_decay_steps=60000 \
    --batch_size=64 \
    --num_workers=16 \
    --steps=60000 \
    --eval_freq=0 \
    --save_freq=10000 \
    --log_freq=100 \
    --wandb.enable=true \
    --wandb.disable_artifact=true \
    --wandb.project=paper \
    --wandb.entity=470620104-technical-university-of-munich;