lerobot-train \
    --job_name=smolvla_stack_red_blocks_100 \
    --output_dir=/root/autodl-tmp/outputs/smolvla_stack_red_blocks_100/ \
    --dataset.repo_id=stack_red_blocks_100 \
    --dataset.root=/root/autodl-tmp/stack_red_blocks_100 \
    --policy.path=lerobot/smolvla_base \
    --policy.push_to_hub=false \
    --policy.scheduler_decay_steps=30000 \
    --batch_size=128 \
    --num_workers=16 \
    --steps=30000 \
    --eval_freq=0 \
    --save_freq=10000 \
    --log_freq=100 \
    --wandb.enable=true \
    --wandb.disable_artifact=true \
    --wandb.project=paper \
    --wandb.entity=470620104-technical-university-of-munich;